version: '3'
services:
  nuxt:
    build:
      context: .
      dockerfile: ./docker/nuxt/Dockerfile
    container_name: nuxt_container
    tty: true
    volumes:
      - ./frontend-app:/app
    command: sh -c "cd /app && yarn install && yarn dev -o"
    ports:
      - 3000:3000
    networks:
      - frontend
  
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./backend-app:/app
    networks:
      - frontend
      - backend
  
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql_container
    platform: linux/x86_64
    env_file:
      - ./docker/mysql/.env_mysql
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/mysql_data:/var/lib/mysql
    ports:
    - 3306:3306
    networks:
      - backend

networks:
  frontend:
      driver: bridge
  backend:
      driver: bridge