// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"backend-app/controller"
	"backend-app/repository"
	"backend-app/service"
	"database/sql"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeControllers(db *sql.DB) (*ControllersSet, error) {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := service.NewUserService(iUserRepository)
	iUserController := controller.NewUserController(iUserService)
	controllersSet := &ControllersSet{
		IUserController: iUserController,
	}
	return controllersSet, nil
}

// wire.go:

// repository
var repositorySet = wire.NewSet(repository.NewUserRepository)

// service
var serviceSet = wire.NewSet(service.NewUserService)

var controllerSet = wire.NewSet(controller.NewUserController)

type ControllersSet struct {
	IUserController controller.IUserController
}
